### PR TITLE
Detect requiresNew for Custom Elements in Chrome

### PR DESCRIPTION
**Pull request by trusktr**

### CODE REVIEW

**Comment by trusktr** [comment]
Added a test for Custom Elements. Does CI run tests in a browser? Looks like it runs only in Node.

**Comment by trusktr** [comment]
At some point I will test in all browsers and update the list of error message regexes.

**Comment by trusktr** [comment]
For reference, here's an example that causes both code paths of #20 and #21 to be executed:

```js
const HTMLElement = newless(window.HTMLElement)
const MyEl = class extends HTMLElement {
    constructor() {
        super()
    }
    connectedCallback() {
        console.log(' ----- connected!')
    }
}

customElements.define('my-el', MyEl)
const el = new MyEl
document.body.appendChild( el )
```

Though in that example `newless` isn't really needed. Where it may really come into play is cases where the user is using `Reflect.construct` manually and passing in custom `new.targets`.

**Comment by Mr0grog** [comment]
> Though in that example newless isn't really needed. Where it may really come into play is cases where the user is using `Reflect.construct` manually and passing in custom `new.targets`.

I don’t understand the point of this example, then. Someone cannot use the `Reflect.construct` polyfill in this library manually. It is not available to outside code.

If you want to make sure Newless lets you do:

```js
const MyElement = newless(class MyElement extends HTMLElement {
  constructor() {
    super()
  }
  connectedCallback() {
    console.log('connected!')
  }
});
customElements.define('my-element', MyElement);
const element = MyElement();
document.body.appendChild(element);
```

Then make an example and test that does that. Otherwise, there is no reason to be using Newless. I’m not sure why it should be changed to support an unrealistic scenario where it is providing no value.

**Comment by Mr0grog** [comment]
OK, I’m going to close this since it seems like you aren’t going to continue to work on it.

**Pull request closed without merging**
